### ISSUE TITLE
more about project

### ISSUE THREAD

**Issue by belka-ew** [dcarp/asynchronous#3]
Can you maybe give more infos about the project in the Readme (or at least here)?
 What are the main purposes of the library?
Is it only for easy porting of python code or is it a general library for async programming?
Is it comparable with vibe:core? What is different from other libraries?
And maybe some general words for not python people..
The thing is I'm looking for a library that creates a layer over libasync with basic async functions and data structures to build on it. And there isn't much I could find.
Thanks

**Comment by dcarp** [comment]
I updated the README a little bit.
Of course `asynchronous` is a general library. It is successfully running in a couple of non-Python projects, commercial inclusive.
In the future there will be more documentation, but don't hold your breath on it. For the time being the python documentation is good enough, although maybe inconvenient for python inexperienced people.
Regarding your use case, I think that `asynchrounous` could be a good match. Just give it a try and send me some feedback you if you encounter any problems.

Schöne Gruße aus Karlsfeld!

**Comment by belka-ew** [comment]
Danke für die schnelle Rückmeldung. Ich bin jetzt beruhigt :) Mir war halt wichtig, dass die Bibliothek verwendet und weiterentwickelt wird. Ich bin noch nicht so erfahren in Sachen wie Streams und asynchrones Programmieren, deswegen brauche eine Grundlage auf der ich aufbauen kann und ich denke, dass asynchronous eine perfekte Lösung sein kann. Ich habe eigentlich schon vorher in den Code geschaut und bin soweit sehr zufrieden. Das ist hervorragende Arbeit.
Ich arbeite gerade an einer Abstraktionsschicht für das Arbeiten mit Dateien (Uploads) und danach werde ich mein SCGI-Modul modifzieren und umschreiben - das ist, wo ich asynchronous erst mal einzusetzen plane.
Wenn du dich fragst, was ich mache, es geht um folgendes Projekt: https://github.com/caraus-ecms/caraus
Good luck!
